version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: beejee
      MYSQL_USER: beejee
      MYSQL_PASSWORD: beejee
    ports:
      - "3308:3306"
    volumes:
      - ./db.sql:/docker-entrypoint-initdb.d/beejee.sql
    tty: true
  php:
    build:
      ./
    volumes:
      - ./:/code
    depends_on:
      - db
  web:
    image: nginx:latest
    ports:
      - "8081:80"
    volumes:
      - ./:/code
      - ./site.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
      - db

